/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
import getStaticUrl from '../../../utils/getStaticUrl';
import SplitWireframeMesh, { SplitWireframeProps } from '../SplitWireframeMesh';

type GLTFResult = GLTF & {
  nodes: {
    straightexport: THREE.Mesh;
  };
  materials: {};
};

const url = getStaticUrl('/static/models/potatoes/fry.gltf');

export default function Fry({
  stroke,
  fill,
  background,
  ...props
}: JSX.IntrinsicElements['group'] & Omit<SplitWireframeProps, 'geometry'>) {
  const { nodes } = (useGLTF(url) as unknown) as GLTFResult;
  return (
    <group rotate={[0, Math.PI, 0]} {...props}>
      <SplitWireframeMesh
        stroke={stroke}
        fill={fill}
        background={background}
        geometry={nodes.straightexport.geometry}
      />
    </group>
  );
}

useGLTF.preload(url);
