/*
 * Mostly auto-generated by: https://github.com/pmndrs/gltfjsx
 * yarn gltfjsx --types potato.gltf
 */

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
import getStaticUrl from '../../../utils/getStaticUrl';
import SplitWireframeMesh, { SplitWireframeProps } from '../SplitWireframeMesh';
import { useScroll } from '../ScrollControls';

type GLTFResult = GLTF & {
  nodes: {
    potato001: THREE.Mesh;
  };
  materials: {};
};

const url = getStaticUrl('/static/models/potatoes/potato.gltf');

export default function Potato({
  stroke,
  fill,
  background,
  ...props
}: JSX.IntrinsicElements['group'] & Omit<SplitWireframeProps, 'geometry'>) {
  const { nodes } = (useGLTF(url) as unknown) as GLTFResult;
  const ref = useRef<THREE.Mesh>();
  const scroll = useScroll();
  useFrame(() => {
    const r = scroll.range(1 / 4 - 0.3, 1 / 4 + 0.3);
    const interpolated = Math.sin(r * Math.PI);
    ref.current.position.y = 50 * interpolated * scroll.offset;
    // Interpolates the range to 0-1-0
    ref.current.scale.setScalar(1 + 5 * interpolated * scroll.offset);
  });
  return (
    <group {...props}>
      <SplitWireframeMesh
        ref={ref}
        stroke={stroke}
        fill={fill}
        background={background}
        geometry={nodes.potato001.geometry}
      />
    </group>
  );
}

useGLTF.preload(url);
