/*
 * Mostly auto-generated by: https://github.com/pmndrs/gltfjsx
 * yarn gltfjsx --types potato.gltf
 */

import * as THREE from 'three';
import React, { forwardRef, useRef } from 'react';
import { useGLTF, useScroll } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
import getStaticUrl from '../../../utils/getStaticUrl';
import ToonOutlineMesh, { ToonOutlineProps } from '../ToonOutlineMesh';

type GLTFResult = GLTF & {
  nodes: {
    potato001: THREE.Mesh;
  };
  materials: {};
};

const url = getStaticUrl('/static/models/potatoes/potato.gltf');

function Potato(props: Omit<ToonOutlineProps, 'geometry'>, ref: React.ForwardedRef<THREE.Mesh>) {
  const { nodes } = (useGLTF(url) as unknown) as GLTFResult;
  return <ToonOutlineMesh ref={ref} {...props} geometry={nodes.potato001.geometry} />;
}

export default forwardRef(Potato);

useGLTF.preload(url);
