/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
import getStaticUrl from '../../../utils/getStaticUrl';
import SplitWireframeMesh, { SplitWireframeProps } from '../SplitWireframeMesh';

const url = getStaticUrl('/static/models/potatoes/waffle.gltf');

type GLTFResult = GLTF & {
  nodes: {
    waffle_export: THREE.Mesh;
  };
  materials: {};
};

export default function Waffle({
  stroke,
  fill,
  background,
  ...props
}: JSX.IntrinsicElements['group'] & Omit<SplitWireframeProps, 'geometry'>) {
  const { nodes } = (useGLTF(url) as unknown) as GLTFResult;
  return (
    <group {...props}>
      <SplitWireframeMesh
        stroke={stroke}
        fill={fill}
        background={background}
        geometry={nodes.waffle_export.geometry}
      />
    </group>
  );
}

useGLTF.preload(url);
