/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
import getStaticUrl from '../../../utils/getStaticUrl';
import SplitWireframeMesh, { SplitWireframeProps } from '../SplitWireframeMesh';
import { useScroll } from '../ScrollControls';

const url = getStaticUrl('/static/models/potatoes/wedge.gltf');

type GLTFResult = GLTF & {
  nodes: {
    wedge_export: THREE.Mesh;
  };
  materials: {};
};

export default function Wedge({
  stroke,
  fill,
  background,
  ...props
}: JSX.IntrinsicElements['group'] & Omit<SplitWireframeProps, 'geometry'>) {
  const ref = useRef<THREE.Mesh>();
  const { nodes } = (useGLTF(url) as unknown) as GLTFResult;
  // const scroll = useScroll();
  // useFrame(() => {
  //   // how to update opacity??
  // });

  return (
    <group {...props}>
      <SplitWireframeMesh
        ref={ref}
        stroke={stroke}
        fill={fill}
        background={background}
        geometry={nodes.wedge_export.geometry}
      />
    </group>
  );
}

useGLTF.preload(url);
